@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Wed Jan 12 11:55:48 +0100 2022
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim sim_sistema_comp_behav -key {Behavioral:sim_1:Functional:sim_sistema_comp} -tclbatch sim_sistema_comp.tcl -view C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/Esercizio9.2_nuovo_vs2019/Esercizio9.2_nuovo_vs2019.srcs/sim_1/imports/Esercizio9.2nuovo/AtoB_tb_behav.wcfg -log simulate.log"
call xsim  sim_sistema_comp_behav -key {Behavioral:sim_1:Functional:sim_sistema_comp} -tclbatch sim_sistema_comp.tcl -view C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/Esercizio9.2_nuovo_vs2019/Esercizio9.2_nuovo_vs2019.srcs/sim_1/imports/Esercizio9.2nuovo/AtoB_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
