#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jan 21 17:05:33 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 05466c3f3a97432bb5da74b71720824f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rete_16_4_tb_behav xil_defaultlib.rete_16_4_tb -log elaborate.log"
xelab -wto 05466c3f3a97432bb5da74b71720824f --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rete_16_4_tb_behav xil_defaultlib.rete_16_4_tb -log elaborate.log

