#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jan 21 16:56:30 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim rete_16_4_tb_behav -key {Behavioral:sim_1:Functional:rete_16_4_tb} -tclbatch rete_16_4_tb.tcl -log simulate.log"
xsim rete_16_4_tb_behav -key {Behavioral:sim_1:Functional:rete_16_4_tb} -tclbatch rete_16_4_tb.tcl -log simulate.log

