#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Dec 21 15:06:27 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto 83588a30e16a469cb7692195fdba91a7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot conv_tb_behav xil_defaultlib.conv_tb -log elaborate.log"
xelab -wto 83588a30e16a469cb7692195fdba91a7 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot conv_tb_behav xil_defaultlib.conv_tb -log elaborate.log

