# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a50ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.cache/wt [current_project]
set_property parent.project_path C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys-a7-50t:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/and_block.vhd
  {C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/imports/Display7Seg - Vivado/anodes_manager.vhd}
  {C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/imports/Display7Seg - Vivado/cathodes_manager.vhd}
  {C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/imports/Display7Seg - Vivado/clock_filter.vhd}
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/contatore.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/conv_bit_integer.vhd
  {C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/imports/Display7Seg - Vivado/counter_mod4.vhd}
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/debouncer.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/delay_block.vhd
  {C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/imports/Display7Seg - Vivado/display_seven_segments.vhd}
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/gestore_modo.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/gestore_set.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/memoria.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/wait_block.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/sistema_contatori.vhd
  C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/sources_1/new/sistema_complessivo.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/constrs_1/imports/davide_420/Nexys-A7-50T-Master.xdc
set_property used_in_implementation false [get_files C:/Users/super/Desktop/magistrale/architetture/progettiVHDL/esercizio5v_c/esercizio5v_c.srcs/constrs_1/imports/davide_420/Nexys-A7-50T-Master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top sistema_complessivo -part xc7a50ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef sistema_complessivo.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file sistema_complessivo_utilization_synth.rpt -pb sistema_complessivo_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
