# -*- coding: utf-8 -*-
"""scriptcreazioneimmagine.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tNPwcUKm1wKJFcFVDZ60qTViyHybuFGN
"""

# Commented out IPython magic to ensure Python compatibility.
# %reset -f
from PIL import Image
import numpy as np
import skimage.io as io
import matplotlib.pyplot as plt
from skimage.transform import resize

x = (np.uint16(io.imread('test.jpg')))

print(x[1][1])
x = np.uint16(resize(x,(200,200),order=1,preserve_range = True))
plt.imshow(x/255)

x = x/255 * 15 #conversione da 0,255 to 0,15 
x = np.uint8(x)
plt.imshow(x/15)

x[280][1]

mem =  [ [ "" for i in range(0,x.shape[1]) ] for j in range(0,x.shape[0]) ]
stringa_pixel = ""
i = 0
j = 0
for i in range(0,x.shape[0]):
    for j in range(0,x.shape[1]):
      stringa_pixel = 'B"'+format(x[i][j][0],"04b") + format(x[i][j][1],"04b") +format(x[i][j][2],"04b")+'"'
      mem[i][j] = stringa_pixel

mem[280][1]

file_mem = open("file_mem.txt","w")
stringa_riga = ""
stringa_output = ""
for i in range(0,x.shape[0]):
  stringa_riga = ""
  for j in range(0,x.shape[1]-1):
      stringa_riga += mem[i][j] + ","
  stringa_riga += mem[0][x.shape[1]-1]
  if( i==x.shape[0]-1): 
    stringa_output = str(i) + " => "+"("+ stringa_riga + " )"
  else:
    stringa_output = str(i) + " => "+"("+ stringa_riga + " )" + ","
  file_mem.writelines(stringa_output)
  file_mem.write("\n")
file_mem.close()

file_mem = open("file_mem.txt","w")
stringa_riga = ""
stringa_output = ""
for i in range(0,x.shape[0]):
    stringa_riga = ""
    stringa_output = "" 
    for j in range(0,x.shape[1]):
      stringa_riga = mem[i][j]
      if( i==x.shape[0]-1): 
        stringa_output = stringa_riga + ", "
      else:
        stringa_output = stringa_riga + ", "
      file_mem.writelines(stringa_output)
      file_mem.write("\n")
file_mem.close()

file_mem = open("file_mem.txt","w")
stringa_riga = ""
stringa_output = ""
for i in range(0,x.shape[0]):
    for j in range(0,x.shape[1]):
      stringa_riga += mem[i][j]

file_mem.writelines(stringa_riga)
file_mem.write("\n")
file_mem.close()

len(stringa_riga)

np.shape(x[:,:,0])

x = (np.uint16(io.imread('test.jpg')))
x = np.uint16(resize(x,(100,100),order=1,preserve_range = True))
plt.imshow(x/255)