#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 16 16:31:39 CET 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto d04268f033204fa4a3bd708e6dd91654 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot shitf_beh_tb_behav xil_defaultlib.shitf_beh_tb -log elaborate.log"
xelab -wto d04268f033204fa4a3bd708e6dd91654 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot shitf_beh_tb_behav xil_defaultlib.shitf_beh_tb -log elaborate.log

