@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Mon Dec 13 16:34:26 +0100 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
echo "xelab -wto 664f109e546d4420b4004e97cba0d1f8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot sim_complessivo_behav xil_defaultlib.sim_complessivo -log elaborate.log"
call xelab  -wto 664f109e546d4420b4004e97cba0d1f8 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot sim_complessivo_behav xil_defaultlib.sim_complessivo -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
